[package]
name = "genpi"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
axum = "0.6.19"
clap = { version = "4.3.17", features = ["derive"] }
rand = "0.8.5"
reqwest = { version = "0.11.18", default-features = false, features = [
  "rustls-tls",
] }
scraper = "0.17.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
time = "0.3.23"
tokio = { version = "1.29.1", features = ["full"] }

[dev-dependencies]
temp-env = "0.3.4"
