[package]
name = "genpi"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"
axum = "0.6.19"
clap = { version = "4.3.17", features = ["derive"] }
hyper = { version = "0.14.27", features = ["full"] }
rand = "0.8.5"
reqwest = { version = "0.11.18", default-features = false, features = [
  "rustls-tls",
] }
scraper = "0.17.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
thiserror = "1.0.44"
time = "0.3.23"
tokio = { version = "1.29.1", features = ["full"] }

[dev-dependencies]
temp-env = "0.3.4"
tower = { version = "0.4.13", features = ["util"] }
